on:
  push: 

jobs:
  started-topic:
      name: Icons
      runs-on: ubuntu-latest
      steps:
        - name: icon
          uses: lowlighter/metrics@latest
          with:
              filename: metrics.plugin.topics.icons.svg
              token: NOT_NEEDED
              base: ""
              plugin_topics: yes
              plugin_topics_limit: 0
              plugin_topics_mode: icons

    
